service: github-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /api/commits
          method: get

plugins:
  - serverless-offline
